version: "3.8"

services:
  corn2p:
    image: ${APP_IMAGE:-corn2p:latest}
    build:
      context: .
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - CORN2P_DATA_DIR=/data
      - CORN2P_UI_PORT=2121
    volumes:
      - corn2p_data:/data
    ports:
      - "2121:2121"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  corn2p_data:
    driver: local
