version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: corn2p
      APP_PORT: 2121

  corn2p:
    image: ${APP_IMAGE:-corn2p:latest}
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - CORN2P_DATA_DIR=/data
      - CORN2P_UI_PORT=2121
    volumes:
      - ${APP_DATA_DIR:-./.umbrel-data}:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
